-- MySQL Script generated by MySQL Workbench
-- Mon May 12 13:40:57 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema muse_art
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema muse_art
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `muse_art` DEFAULT CHARACTER SET utf8mb4 ;
USE `muse_art` ;

-- -----------------------------------------------------
-- Table `muse_art`.`author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muse_art`.`author` ;

CREATE TABLE IF NOT EXISTS `muse_art`.`author` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `dob` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `muse_art`.`article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muse_art`.`article` ;

CREATE TABLE IF NOT EXISTS `muse_art`.`article` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `classification` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `author_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_1` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_1`
    FOREIGN KEY (`author_id`)
    REFERENCES `muse_art`.`author` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `muse_art`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muse_art`.`tag` ;

CREATE TABLE IF NOT EXISTS `muse_art`.`tag` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `muse_art`.`article_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muse_art`.`article_tag` ;

CREATE TABLE IF NOT EXISTS `muse_art`.`article_tag` (
  `article_id` INT(11) NOT NULL,
  `tag_id` INT(11) NOT NULL,
  UNIQUE INDEX `article_id` (`article_id` ASC, `tag_id` ASC) VISIBLE,
  INDEX `fk_2` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `fk_1`
    FOREIGN KEY (`article_id`)
    REFERENCES `muse_art`.`article` (`id`),
  CONSTRAINT `fk_2`
    FOREIGN KEY (`tag_id`)
    REFERENCES `muse_art`.`tag` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `muse_art`.`artwork`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muse_art`.`artwork` ;

CREATE TABLE IF NOT EXISTS `muse_art`.`artwork` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `date_display` DATE NULL DEFAULT NULL,
  `place_of_origin` VARCHAR(255) NULL DEFAULT NULL,
  `fiscal_year` YEAR(4) NULL DEFAULT NULL,
  `dimensions` VARCHAR(255) NULL DEFAULT NULL,
  `credit_line` VARCHAR(255) NULL DEFAULT NULL,
  `inscription` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `artist_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_1` (`artist_id` ASC) VISIBLE,
  CONSTRAINT `fk_1`
    FOREIGN KEY (`artist_id`)
    REFERENCES `muse_art`.`author` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `muse_art`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muse_art`.`user` ;

CREATE TABLE IF NOT EXISTS `muse_art`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 240001
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `muse_art`.`artwork_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muse_art`.`artwork_comment` ;

CREATE TABLE IF NOT EXISTS `muse_art`.`artwork_comment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `artwork_id` INT(11) NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_1` (`user_id` ASC) VISIBLE,
  INDEX `fk_2` (`artwork_id` ASC) VISIBLE,
  CONSTRAINT `fk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `muse_art`.`user` (`id`),
  CONSTRAINT `fk_2`
    FOREIGN KEY (`artwork_id`)
    REFERENCES `muse_art`.`artwork` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `muse_art`.`artwork_reaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muse_art`.`artwork_reaction` ;

CREATE TABLE IF NOT EXISTS `muse_art`.`artwork_reaction` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `artwork_id` INT(11) NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id` (`user_id` ASC, `artwork_id` ASC) VISIBLE,
  INDEX `fk_2` (`artwork_id` ASC) VISIBLE,
  CONSTRAINT `fk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `muse_art`.`user` (`id`),
  CONSTRAINT `fk_2`
    FOREIGN KEY (`artwork_id`)
    REFERENCES `muse_art`.`artwork` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `muse_art`.`artwork_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muse_art`.`artwork_tag` ;

CREATE TABLE IF NOT EXISTS `muse_art`.`artwork_tag` (
  `artwork_id` INT(11) NOT NULL,
  `tag_id` INT(11) NOT NULL,
  UNIQUE INDEX `artwork_id` (`artwork_id` ASC, `tag_id` ASC) VISIBLE,
  INDEX `fk_2` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `fk_1`
    FOREIGN KEY (`artwork_id`)
    REFERENCES `muse_art`.`artwork` (`id`),
  CONSTRAINT `fk_2`
    FOREIGN KEY (`tag_id`)
    REFERENCES `muse_art`.`tag` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `muse_art`.`bookmark`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muse_art`.`bookmark` ;

CREATE TABLE IF NOT EXISTS `muse_art`.`bookmark` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `target_type` VARCHAR(50) NOT NULL,
  `target_id` INT(11) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id` (`user_id` ASC, `target_type` ASC, `target_id` ASC) VISIBLE,
  CONSTRAINT `fk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `muse_art`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `muse_art`.`store_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muse_art`.`store_item` ;

CREATE TABLE IF NOT EXISTS `muse_art`.`store_item` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `classification` VARCHAR(100) NULL DEFAULT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `stock_quantity` INT(11) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `muse_art`.`cart_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muse_art`.`cart_item` ;

CREATE TABLE IF NOT EXISTS `muse_art`.`cart_item` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `item_id` INT(11) NOT NULL,
  `quantity` INT(11) NOT NULL,
  `added_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id` (`user_id` ASC, `item_id` ASC) VISIBLE,
  INDEX `fk_2` (`item_id` ASC) VISIBLE,
  CONSTRAINT `fk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `muse_art`.`user` (`id`),
  CONSTRAINT `fk_2`
    FOREIGN KEY (`item_id`)
    REFERENCES `muse_art`.`store_item` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `muse_art`.`exhibition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muse_art`.`exhibition` ;

CREATE TABLE IF NOT EXISTS `muse_art`.`exhibition` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `start_time` DATETIME NULL DEFAULT NULL,
  `end_time` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `status` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `muse_art`.`exhibition_artwork`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muse_art`.`exhibition_artwork` ;

CREATE TABLE IF NOT EXISTS `muse_art`.`exhibition_artwork` (
  `exhibition_id` INT(11) NOT NULL,
  `artwork_id` INT(11) NOT NULL,
  UNIQUE INDEX `exhibition_id` (`exhibition_id` ASC, `artwork_id` ASC) VISIBLE,
  INDEX `fk_2` (`artwork_id` ASC) VISIBLE,
  CONSTRAINT `fk_1`
    FOREIGN KEY (`exhibition_id`)
    REFERENCES `muse_art`.`exhibition` (`id`),
  CONSTRAINT `fk_2`
    FOREIGN KEY (`artwork_id`)
    REFERENCES `muse_art`.`artwork` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `muse_art`.`exhibition_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muse_art`.`exhibition_comment` ;

CREATE TABLE IF NOT EXISTS `muse_art`.`exhibition_comment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `exhibition_id` INT(11) NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_1` (`user_id` ASC) VISIBLE,
  INDEX `fk_2` (`exhibition_id` ASC) VISIBLE,
  CONSTRAINT `fk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `muse_art`.`user` (`id`),
  CONSTRAINT `fk_2`
    FOREIGN KEY (`exhibition_id`)
    REFERENCES `muse_art`.`exhibition` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `muse_art`.`exhibition_reaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muse_art`.`exhibition_reaction` ;

CREATE TABLE IF NOT EXISTS `muse_art`.`exhibition_reaction` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `exhibition_id` INT(11) NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id` (`user_id` ASC, `exhibition_id` ASC) VISIBLE,
  INDEX `fk_2` (`exhibition_id` ASC) VISIBLE,
  CONSTRAINT `fk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `muse_art`.`user` (`id`),
  CONSTRAINT `fk_2`
    FOREIGN KEY (`exhibition_id`)
    REFERENCES `muse_art`.`exhibition` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `muse_art`.`exhibition_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muse_art`.`exhibition_tag` ;

CREATE TABLE IF NOT EXISTS `muse_art`.`exhibition_tag` (
  `exhibition_id` INT(11) NOT NULL,
  `tag_id` INT(11) NOT NULL,
  UNIQUE INDEX `exhibition_id` (`exhibition_id` ASC, `tag_id` ASC) VISIBLE,
  INDEX `fk_2` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `fk_1`
    FOREIGN KEY (`exhibition_id`)
    REFERENCES `muse_art`.`exhibition` (`id`),
  CONSTRAINT `fk_2`
    FOREIGN KEY (`tag_id`)
    REFERENCES `muse_art`.`tag` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
